# Generated by Django 4.0.4 on 2022-05-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirrecion'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reference_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia de la dirección'),
        ),
    ]
